### ISSUE TITLE
Error fetching public IP

### ISSUE THREAD

**Issue by saket424** [longern/browser-broadcast-box#1]
Where can I specify the PUBLIC_IP in a .env file? I am getting a public IP not found error

```
async function init() {
  for (const envPath of ["./.env.local", "./.env"]) {
    try {
      loadSync({ envPath: envPath, export: true });
    } catch (_e) {
      // Ignore
    }
  }

  if (!Deno.env.get("PUBLIC_IP")) {
    const publicIp = await detectPublicIp();
    if (publicIp) Deno.env.set("PUBLIC_IP", publicIp);
  }

  if (Deno.env.get("BEARER_TOKEN")) console.log("Bearer token is set");

  const dbPath = Deno.env.get("DB") || "./db.sqlite3";
  const DB = new D1Database(dbPath);
  const migrations = new TextDecoder().decode(
    Deno.readFileSync("./server/migrations.sql")
  );
  DB.exec(migrations);
  bindings = { ...Deno.env.toObject(), DB };
}

```

```
anand@chi1:~/browser-broadcast-box$ docker compose up
[+] Running 6/6
 ⠿ chrome Pulled                                                          24.4s
   ⠿ f56be85fc22e Pull complete                                            0.9s
   ⠿ c691cfdca2fd Pull complete                                           21.3s
   ⠿ bf2668cbf258 Pull complete                                           21.4s
   ⠿ 34dc035d5a52 Pull complete                                           21.5s
   ⠿ 4f4fb700ef54 Pull complete                                           21.7s
[+] Running 3/3
 ⠿ Network browser-broadcast-box_default      Created                      0.1s
 ⠿ Container browser-broadcast-box-backend-1  Created                      0.1s
 ⠿ Container browser-broadcast-box-chrome-1   Created                      0.0s
Attaching to browser-broadcast-box-backend-1, browser-broadcast-box-chrome-1
browser-broadcast-box-backend-1  | Task prod deno run -A server/main.ts
browser-broadcast-box-backend-1  | Fetching public IP...
browser-broadcast-box-backend-1  | Listening on http://localhost:11733/
browser-broadcast-box-chrome-1   | [0412/170034.073710:ERROR:headless_shell.cc(255)] Multiple targets are not supported.
browser-broadcast-box-chrome-1 exited with code 1
browser-broadcast-box-backend-1  | No public IP found
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Running 1/2
 ⠿ Container browser-broadcast-box-chrome-1   Stopped                      0.0s
[+] Running 2/2owser-broadcast-box-backend-1  Stopping                     0.2s
[+] Running 0/1owser-broadcast-box-chrome-1   Stopped                      0.0s
 ⠿ Container browser-broadcast-box-backend-1  Error while Killing          0.2s
canceled
anand@chi1:~/browser-broadcast-box$
```

**Comment by saket424** [comment]
I passed the PUBLIC_IP as an environmental variable in the docker-compose.yml

I now get this error "Multiple targets are not supported."

```
anand@chi1:~/browser-broadcast-box$ docker compose up
[+] Running 3/2
 ⠿ Network browser-broadcast-box_default      Created                      0.1s
 ⠿ Container browser-broadcast-box-backend-1  Created                      0.1s
 ⠿ Container browser-broadcast-box-chrome-1   Created                      0.1s
Attaching to browser-broadcast-box-backend-1, browser-broadcast-box-chrome-1
browser-broadcast-box-backend-1  | Task prod deno run -A server/main.ts
browser-broadcast-box-backend-1  | Bearer token is set
browser-broadcast-box-backend-1  | Listening on http://localhost:11733/
browser-broadcast-box-chrome-1   | [0417/153831.431937:ERROR:headless_shell.cc(255)] Multiple targets are not supported.
browser-broadcast-box-chrome-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...

```

**Comment by longern** [comment]
Did you modify `docker-compose.yml`? Pasting the file content may be helpful (mask your secret).

**Comment by saket424** [comment]
here is my docker-compose.yml

```
version: "3"
services:
  backend:
    build: .
    ports:
      - "11733:11733"
    networks:
      - default
    environment:
      - WEBSOCKET_WHITELIST=172.20.0.3
      - PUBLIC_IP=redacted
      - BEARER_TOKEN=redacted
  chrome:
    image: zenika/alpine-chrome:112
    command: chromium-browser --headless --no-sandbox --remote-debugging-port=0 http://backend:11733/backend/?s=backend:11733
    networks:
      default:
        ipv4_address: 172.20.0.3

    depends_on:
      - backend

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
```
